/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1andresimery;

import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.graphstream.graph.*;
import org.graphstream.ui.swingViewer.*;
import org.graphstream.ui.view.*;


/** Esta clase es la ventana principal de todo el programa y muestra el grafo visualizado
 *
 * @author andresimery
 */
public class Ventana1 extends javax.swing.JFrame {
     //Campos de la clase
    private static Graph graph;
    private static Grafo grafo;
    
    /**
     * Constructor
     * @param graph El parámetro graph recibe el grafo de GraphStream para poder visualizarlo
     * @param grafo El parámetro grafo recibe el grafo de creado en el programa para poder manejar la información
     */
    public Ventana1(Graph graph, Grafo grafo) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        createUIComponents(graph);
        this.graph = graph;
        this.grafo = grafo;
        
        
    }
    
    /**
     * Getter
     * 
     */
    public Grafo getGrafo() {
        return this.grafo;
    }
    
    /**
     * Actualiza el grafo de GraphStream
     * 
     */
    public void updateGraph() {
        this.graph = this.grafo.grafoToGraphStream();
        jPanelGraph.removeAll();
        createUIComponents(this.graph);
    }
    
    /**
     * Agrega un usuario al grafo
     * 
     * @param user el usuario que se va a agregar
     */
    public void addUser(User user) {
        this.grafo.addUser(user);
        
        
        updateGraph();
    }
    
    /**
     * Agrega una relación al grafo
     * 
     * @param relation la relación que se va a agregar
     */
    public void addRelation(Relation relation) {
        this.grafo.addRelation(relation);

        
        updateGraph();
    }
    
    /**
     * Agrega el grafo de GraphStream al jPanel
     * 
     * @param graph el grafo de graphstream que va a agregar
     */
    public void createUIComponents(Graph graph) {
        System.setProperty("org.graphstream.ui", "swing");

        Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        
        viewer.enableAutoLayout();
        ViewPanel viewPanel = viewer.addDefaultView(false);

        jPanelGraph.setBorder(BorderFactory.createLineBorder(null, 0));
        jPanelGraph.add(viewPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGraph = new javax.swing.JPanel();
        jButtonNewUser = new javax.swing.JButton();
        jButtonNewRelation = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonLoad = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jButtonDeleteRelation = new javax.swing.JButton();
        jButtonDFT = new javax.swing.JButton();
        jButtonBFT = new javax.swing.JButton();
        jButtonShowLists = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelGraph.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanelGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 780, 530));

        jButtonNewUser.setText("Nuevo Usuario");
        jButtonNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewUserActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, -1));

        jButtonNewRelation.setText("Nueva Relacion");
        jButtonNewRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewRelationActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNewRelation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButtonSave.setText("Guardar");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        jButtonLoad.setText("Cargar Archivo");
        jButtonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jButtonDeleteUser.setText("Borrar Usuario");
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 120, -1));

        jButtonDeleteRelation.setText("Borrar Relacion");
        jButtonDeleteRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteRelationActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeleteRelation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jButtonDFT.setText("DFT");
        jButtonDFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDFTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jButtonBFT.setText("BFT");
        jButtonBFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBFTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jButtonShowLists.setText("Mostrar Listas");
        jButtonShowLists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowListsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowLists, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Va a la ventana de NewUserWindow
     *
     */
    private void jButtonNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewUserActionPerformed
        new NewUserWindow(this);
        setVisible(false);
    }//GEN-LAST:event_jButtonNewUserActionPerformed

    /**
     * Va a la ventana de NewRelationByNameWindow
     *
     */
    private void jButtonNewRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewRelationActionPerformed
        new NewRelationByNameWindow(this);
        setVisible(false);
    }//GEN-LAST:event_jButtonNewRelationActionPerformed

    /**
     * Guarda en el archivo de texto
     *
     */
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        (new Function()).writeTxt(grafo);
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * Carga un archivo de texto
     *
     */
    private void jButtonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadActionPerformed
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(null);
        File path = file.getSelectedFile();
        this.grafo = (new Function()).readTxt(path, this.grafo);
        this.grafo.getUsers().printListUser(this.grafo.getUsers());
        
        setVisible(false);
        updateGraph();
        setVisible(true);
    }//GEN-LAST:event_jButtonLoadActionPerformed

    /**
     * Va a la ventana de DeleteUserWindow
     *
     */
    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        new DeleteUserWindow(this);
        setVisible(false);
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    /**
     * Recorre con Depth First Traversal y dice la cantidad de islas que hay
     *
     */
    private void jButtonDFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDFTActionPerformed
        JOptionPane.showMessageDialog(null, "Existen " + this.grafo.depthFirstTraversal() + " islas en el grafo.");
    }//GEN-LAST:event_jButtonDFTActionPerformed

    /**
     * Recorre con Breadth First Traversal y dice la cantidad de islas que hay
     *
     */
    private void jButtonBFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBFTActionPerformed
        JOptionPane.showMessageDialog(null, "Existen " + this.grafo.breadthDepthTraversal() + " islas en el grafo.");
    }//GEN-LAST:event_jButtonBFTActionPerformed

    /**
     * Va a la ventana de DeleteRelationWindow
     *
     */
    private void jButtonDeleteRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteRelationActionPerformed
        new DeleteRelationWindow(this);
        setVisible(false);
    }//GEN-LAST:event_jButtonDeleteRelationActionPerformed

    /**
     * Va a la ventana de ShowLists
     *
     */
    private void jButtonShowListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowListsActionPerformed
        new ListsWindow(this);
        setVisible(false);
    }//GEN-LAST:event_jButtonShowListsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1(graph, grafo).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBFT;
    private javax.swing.JButton jButtonDFT;
    private javax.swing.JButton jButtonDeleteRelation;
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonLoad;
    private javax.swing.JButton jButtonNewRelation;
    private javax.swing.JButton jButtonNewUser;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonShowLists;
    private javax.swing.JPanel jPanelGraph;
    // End of variables declaration//GEN-END:variables
}
